controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# page_contact:
#     path: /contact
#     controller: App\Controller\PagesController::contact

# page_cgu:
#     path: /cgu
#     controller: App\Controller\PagesController::cgu